/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.gamemessages.IncomingMessage');
goog.provide('proto.gamemessages.IncomingMessage.Type');

goog.require('jspb.Message');
goog.require('proto.gamemessages.Handshake');
goog.require('proto.gamemessages.Shoot');
goog.require('proto.gamemessages.Spawn');
goog.require('proto.gamemessages.Thrust');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gamemessages.IncomingMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.gamemessages.IncomingMessage.oneofGroups_);
};
goog.inherits(proto.gamemessages.IncomingMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gamemessages.IncomingMessage.displayName = 'proto.gamemessages.IncomingMessage';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.gamemessages.IncomingMessage.oneofGroups_ = [[5,9,13,17]];

/**
 * @enum {number}
 */
proto.gamemessages.IncomingMessage.MsgCase = {
  MSG_NOT_SET: 0,
  THRUST: 5,
  SHOOT: 9,
  HANDSHAKE: 13,
  SPAWN: 17
};

/**
 * @return {proto.gamemessages.IncomingMessage.MsgCase}
 */
proto.gamemessages.IncomingMessage.prototype.getMsgCase = function() {
  return /** @type {proto.gamemessages.IncomingMessage.MsgCase} */(jspb.Message.computeOneofCase(this, proto.gamemessages.IncomingMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gamemessages.IncomingMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.gamemessages.IncomingMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gamemessages.IncomingMessage} msg The msg instance to transform.
 * @return {!Object}
 */
proto.gamemessages.IncomingMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: msg.getType(),
    thrust: (f = msg.getThrust()) && proto.gamemessages.Thrust.toObject(includeInstance, f),
    shoot: (f = msg.getShoot()) && proto.gamemessages.Shoot.toObject(includeInstance, f),
    handshake: (f = msg.getHandshake()) && proto.gamemessages.Handshake.toObject(includeInstance, f),
    spawn: (f = msg.getSpawn()) && proto.gamemessages.Spawn.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.gamemessages.IncomingMessage} The clone.
 */
proto.gamemessages.IncomingMessage.prototype.cloneMessage = function() {
  return /** @type {!proto.gamemessages.IncomingMessage} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Type type = 1;
 * @return {!proto.gamemessages.IncomingMessage.Type}
 */
proto.gamemessages.IncomingMessage.prototype.getType = function() {
  return /** @type {!proto.gamemessages.IncomingMessage.Type} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.gamemessages.IncomingMessage.Type} value  */
proto.gamemessages.IncomingMessage.prototype.setType = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional Thrust thrust = 5;
 * @return {proto.gamemessages.Thrust}
 */
proto.gamemessages.IncomingMessage.prototype.getThrust = function() {
  return /** @type{proto.gamemessages.Thrust} */ (
    jspb.Message.getWrapperField(this, proto.gamemessages.Thrust, 5));
};


/** @param {proto.gamemessages.Thrust|undefined} value  */
proto.gamemessages.IncomingMessage.prototype.setThrust = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.gamemessages.IncomingMessage.oneofGroups_[0], value);
};


proto.gamemessages.IncomingMessage.prototype.clearThrust = function() {
  this.setThrust(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.gamemessages.IncomingMessage.prototype.hasThrust = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Shoot shoot = 9;
 * @return {proto.gamemessages.Shoot}
 */
proto.gamemessages.IncomingMessage.prototype.getShoot = function() {
  return /** @type{proto.gamemessages.Shoot} */ (
    jspb.Message.getWrapperField(this, proto.gamemessages.Shoot, 9));
};


/** @param {proto.gamemessages.Shoot|undefined} value  */
proto.gamemessages.IncomingMessage.prototype.setShoot = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.gamemessages.IncomingMessage.oneofGroups_[0], value);
};


proto.gamemessages.IncomingMessage.prototype.clearShoot = function() {
  this.setShoot(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.gamemessages.IncomingMessage.prototype.hasShoot = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional Handshake handshake = 13;
 * @return {proto.gamemessages.Handshake}
 */
proto.gamemessages.IncomingMessage.prototype.getHandshake = function() {
  return /** @type{proto.gamemessages.Handshake} */ (
    jspb.Message.getWrapperField(this, proto.gamemessages.Handshake, 13));
};


/** @param {proto.gamemessages.Handshake|undefined} value  */
proto.gamemessages.IncomingMessage.prototype.setHandshake = function(value) {
  jspb.Message.setOneofWrapperField(this, 13, proto.gamemessages.IncomingMessage.oneofGroups_[0], value);
};


proto.gamemessages.IncomingMessage.prototype.clearHandshake = function() {
  this.setHandshake(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.gamemessages.IncomingMessage.prototype.hasHandshake = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional Spawn spawn = 17;
 * @return {proto.gamemessages.Spawn}
 */
proto.gamemessages.IncomingMessage.prototype.getSpawn = function() {
  return /** @type{proto.gamemessages.Spawn} */ (
    jspb.Message.getWrapperField(this, proto.gamemessages.Spawn, 17));
};


/** @param {proto.gamemessages.Spawn|undefined} value  */
proto.gamemessages.IncomingMessage.prototype.setSpawn = function(value) {
  jspb.Message.setOneofWrapperField(this, 17, proto.gamemessages.IncomingMessage.oneofGroups_[0], value);
};


proto.gamemessages.IncomingMessage.prototype.clearSpawn = function() {
  this.setSpawn(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.gamemessages.IncomingMessage.prototype.hasSpawn = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * @enum {number}
 */
proto.gamemessages.IncomingMessage.Type = {
  THRUST: 0,
  SHOOT: 1,
  HANDSHAKE: 2,
  SPAWN: 3
};

