/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.gamemessages.Scene');
goog.provide('proto.gamemessages.Scene.Object');
goog.provide('proto.gamemessages.Scene.Object.Type');

goog.require('jspb.Message');
goog.require('proto.vec.vec2f');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gamemessages.Scene = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gamemessages.Scene, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gamemessages.Scene.displayName = 'proto.gamemessages.Scene';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gamemessages.Scene.prototype.toObject = function(opt_includeInstance) {
  return proto.gamemessages.Scene.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gamemessages.Scene} msg The msg instance to transform.
 * @return {!Object}
 */
proto.gamemessages.Scene.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.gamemessages.Scene} The clone.
 */
proto.gamemessages.Scene.prototype.cloneMessage = function() {
  return /** @type {!proto.gamemessages.Scene} */ (jspb.Message.cloneMessage(this));
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gamemessages.Scene.Object = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gamemessages.Scene.Object, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.gamemessages.Scene.Object.displayName = 'proto.gamemessages.Scene.Object';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gamemessages.Scene.Object.prototype.toObject = function(opt_includeInstance) {
  return proto.gamemessages.Scene.Object.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gamemessages.Scene.Object} msg The msg instance to transform.
 * @return {!Object}
 */
proto.gamemessages.Scene.Object.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: msg.getType(),
    position: (f = msg.getPosition()) && proto.vec.vec2f.toObject(includeInstance, f),
    velocity: (f = msg.getVelocity()) && proto.vec.vec2f.toObject(includeInstance, f),
    lastprocessedcommand: msg.getLastprocessedcommand()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.gamemessages.Scene.Object} The clone.
 */
proto.gamemessages.Scene.Object.prototype.cloneMessage = function() {
  return /** @type {!proto.gamemessages.Scene.Object} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional Type type = 1;
 * @return {!proto.gamemessages.Scene.Object.Type}
 */
proto.gamemessages.Scene.Object.prototype.getType = function() {
  return /** @type {!proto.gamemessages.Scene.Object.Type} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.gamemessages.Scene.Object.Type} value  */
proto.gamemessages.Scene.Object.prototype.setType = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional vec.vec2f position = 2;
 * @return {proto.vec.vec2f}
 */
proto.gamemessages.Scene.Object.prototype.getPosition = function() {
  return /** @type{proto.vec.vec2f} */ (
    jspb.Message.getWrapperField(this, proto.vec.vec2f, 2));
};


/** @param {proto.vec.vec2f|undefined} value  */
proto.gamemessages.Scene.Object.prototype.setPosition = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.gamemessages.Scene.Object.prototype.clearPosition = function() {
  this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.gamemessages.Scene.Object.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional vec.vec2f velocity = 3;
 * @return {proto.vec.vec2f}
 */
proto.gamemessages.Scene.Object.prototype.getVelocity = function() {
  return /** @type{proto.vec.vec2f} */ (
    jspb.Message.getWrapperField(this, proto.vec.vec2f, 3));
};


/** @param {proto.vec.vec2f|undefined} value  */
proto.gamemessages.Scene.Object.prototype.setVelocity = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.gamemessages.Scene.Object.prototype.clearVelocity = function() {
  this.setVelocity(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.gamemessages.Scene.Object.prototype.hasVelocity = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 lastProcessedCommand = 4;
 * @return {number}
 */
proto.gamemessages.Scene.Object.prototype.getLastprocessedcommand = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.gamemessages.Scene.Object.prototype.setLastprocessedcommand = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.gamemessages.Scene.Object.Type = {
  FOOD: 0,
  HARVESTER: 1,
  SMALLSHIP: 2
};

